"""
Output file generator: creates summary.md and extraction.json for each paper.

Files are written to:
  /data/papers/{paper_id}/summary.md
  /data/papers/{paper_id}/extraction.json
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.core.config import get_settings
from app.core.logging import get_logger
from app.models.extraction import ExtractionRecord
from app.models.paper import Paper
from app.schemas.extraction import LLMExtractionOutput
from app.services.storage import get_storage

log = get_logger(__name__)


class OutputGenerator:

    def __init__(self):
        self.storage = get_storage()
        self.settings = get_settings()

    def generate_summary(
        self,
        paper: Paper,
        extraction: LLMExtractionOutput,
        paper_id: uuid.UUID,
    ) -> Path:
        """Generate a human-readable markdown summary file."""
        path = self.storage.summary_path(paper_id)

        lines = [
            f"# {extraction.bibliographic_info.title if extraction.bibliographic_info and extraction.bibliographic_info.title else paper.original_filename}",
            "",
            f"**Generated by PaperLens** | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Schema version:** {extraction.schema_version}",
            "",
            "---",
            "",
            "## Summary",
            "",
            extraction.summary,
            "",
        ]

        # Bibliographic info
        if bib := extraction.bibliographic_info:
            lines += [
                "## Bibliographic Information",
                "",
                f"- **Title:** {bib.title or 'N/A'}",
                f"- **Journal:** {bib.journal or 'N/A'}",
                f"- **Authors:** {', '.join(bib.authors) if bib.authors else 'N/A'}",
                f"- **Year:** {bib.year or 'N/A'}",
                f"- **DOI:** {bib.doi or 'N/A'}",
                f"- **Volume/Issue/Pages:** {bib.volume or '-'}/{bib.issue or '-'}/{bib.pages or '-'}",
                "",
            ]

        # Materials
        if extraction.materials:
            lines += ["## Materials / Systems", ""]
            for i, mat in enumerate(extraction.materials, 1):
                lines.append(f"### Material {i}: {mat.name or 'Unknown'}")
                if mat.composition:
                    lines.append(f"- **Composition:** {mat.composition}")
                if mat.substrate:
                    lines.append(f"- **Substrate:** {mat.substrate}")
                if mat.crystal_structure:
                    lines.append(f"- **Crystal structure:** {mat.crystal_structure}")
                if mat.device_structure:
                    lines.append(f"- **Device structure:** {mat.device_structure}")
                if mat.layer_stack:
                    lines.append(f"- **Layer stack:** {mat.layer_stack}")
                lines.append("")

        # Process conditions
        if extraction.process_conditions:
            lines += ["## Processing Conditions (Input Variables)", ""]
            lines.append("| Parameter | Value | Unit | Role | Confidence | Inferred? |")
            lines.append("|-----------|-------|------|------|-----------|-----------|")
            for cond in extraction.process_conditions:
                val = str(cond.value_numeric) if cond.value_numeric is not None else (cond.value_text or "N/A")
                conf = f"{cond.confidence:.2f}" if cond.confidence is not None else "N/A"
                lines.append(
                    f"| {cond.parameter_name} | {val} | {cond.unit or 'N/A'} "
                    f"| {cond.variable_role} | {conf} | {'Yes' if cond.is_inferred else 'No'} |"
                )
            lines.append("")

        # Results
        if extraction.result_properties:
            lines += ["## Experimental Results (Output Variables)", ""]
            lines.append("| Property | Value | Min | Max | Unit | Conditions | Confidence | Review? |")
            lines.append("|----------|-------|-----|-----|------|------------|-----------|---------|")
            for rp in extraction.result_properties:
                val = str(rp.value_numeric) if rp.value_numeric is not None else (rp.value_text or "N/A")
                val_min = str(rp.value_min) if rp.value_min is not None else "-"
                val_max = str(rp.value_max) if rp.value_max is not None else "-"
                conf = f"{rp.confidence:.2f}" if rp.confidence is not None else "N/A"
                lines.append(
                    f"| {rp.property_name} | {val} | {val_min} | {val_max} "
                    f"| {rp.unit or 'N/A'} | {rp.conditions or 'N/A'} | {conf} | {'⚠️ Yes' if rp.needs_review else 'No'} |"
                )
            lines.append("")

        # Measurement methods
        if extraction.measurement_methods:
            lines += ["## Characterization Methods", ""]
            for m in extraction.measurement_methods:
                lines.append(f"- **{m.technique_name}** ({m.category or 'N/A'}): {m.description or ''}")
            lines.append("")

        # Outcome
        if outcome := extraction.outcome:
            lines += ["## Key Findings and Outcomes", ""]
            if outcome.main_findings:
                lines += ["### Main Findings", "", outcome.main_findings, ""]
            if outcome.claimed_mechanism:
                lines += ["### Claimed Mechanism", "", outcome.claimed_mechanism, ""]
            if outcome.limitations:
                lines += ["### Limitations", "", outcome.limitations, ""]
            if outcome.notable_novelty:
                lines += ["### Notable Novelty", "", outcome.notable_novelty, ""]
            if outcome.relevant_for_optimization is not None:
                rel = "**Yes** ✓" if outcome.relevant_for_optimization else "No"
                lines.append(f"**Relevant for optimization:** {rel}")
            lines.append("")

        # Warnings and review flags
        if extraction.extraction_warnings or extraction.fields_needing_review:
            lines += ["## Extraction Quality Notes", ""]
            if extraction.extraction_warnings:
                lines.append("### Warnings")
                for w in extraction.extraction_warnings:
                    lines.append(f"- ⚠️ {w}")
                lines.append("")
            if extraction.fields_needing_review:
                lines.append("### Fields Needing Human Review")
                for f in extraction.fields_needing_review:
                    lines.append(f"- 🔍 `{f}`")
                lines.append("")

        content = "\n".join(lines)
        path.write_text(content, encoding="utf-8")
        log.info("Summary written", path=str(path), chars=len(content))
        return path

    def generate_extraction_json(
        self,
        extraction: LLMExtractionOutput,
        paper_id: uuid.UUID,
        paper_metadata: Optional[dict] = None,
    ) -> Path:
        """Generate machine-readable extraction.json file."""
        path = self.storage.extraction_json_path(paper_id)

        output = {
            "paper_id": str(paper_id),
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "schema_version": extraction.schema_version,
            "extraction": extraction.model_dump(exclude_none=False),
        }
        if paper_metadata:
            output["paper_metadata"] = paper_metadata

        path.write_text(
            json.dumps(output, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )
        log.info("Extraction JSON written", path=str(path))
        return path


_generator: Optional[OutputGenerator] = None


def get_output_generator() -> OutputGenerator:
    global _generator
    if _generator is None:
        _generator = OutputGenerator()
    return _generator
